trigger:
- master

resources:
- repo: self

variables:
  tag: 23 #'$(Build.BuildId)'
# stage1 : Build the docker image and publish the K8S Files
stages:
- stage: Build 
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    #- task: Docker@2  # Build the docker images
     # inputs:
      #  containerRegistry: 'Docker hub'
       # repository: 'mohamedomri/medomlearning'
       # command: 'buildAndPush'
       # Dockerfile: '**/Dockerfile'
       # tags: '$(tag)'
        
    - task: PublishBuildArtifacts@1 #Publish the K8S Files
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy 
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2 #Download the K8S files
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'medomlearning-serviceaccount'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'mohamedomri/medomlearning:$(tag)'