trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build FirstJob  
- stage: DevDeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo deploy DevDeploy
- stage: ProdDeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo deploy ProdDeploy
    - bash: echo deploy ProdDeploy step2
  